### ISSUE TITLE
Navigation module needs reference page

### ISSUE THREAD

**Issue by richardhj** [erdmannfreunde/contao-onepage-navigation#1]
The regular navigation module has the settings "reference page" and "define root".
It would be nice to bring these settings back to your article navigation module.
Doing so, you should be able to place the navigation outside the page with the one page structure and still see the navigation items.

Please see [this page](https://www.local-derby.de/). When you click on the page "Impressum", the navigation is gone but I would like to keep the navigation there.

**Comment by bastibuck** [comment]
Thanks for your input! Will be in a new release soon.

Added in https://github.com/ErdmannFreunde/contao-onepage-navigation/commit/e50b56ffa311486af176ef5ece685249e7a48fbc
