### ISSUE TITLE
[Contao 4.4] Reference Page not working anymore

### ISSUE THREAD

**Issue by denniserdmann** [erdmannfreunde/contao-onepage-navigation#10]
The Option Reference Page, where you can select a page, which articles should be used for the navigation is not working anymore.

**Comment by Ma3xl3** [comment]
Yes, it worked in 1.1.0.

The `$intPageID` is not overwritten in the following if condition:

https://github.com/ErdmannFreunde/contao-onepage-navigation/blob/df90e66238a2ca81ab7b688e7b0be69ccf01d75a/src/Modules/ModuleOnepageNavigation.php#L60
