### ISSUE TITLE
Scrolling on Touch Devices

### ISSUE THREAD

**Issue by intradesign** [erdmannfreunde/contao-onepage-navigation#14]
Hallo,

auf einer Website funktioniert bei Verwendung er onepagenavigation das normale Scrolling auf Touch-Geräten nicht mehr. Beim Scrollen wird immer auch der nächste Onepage-Artikel angesprungen. Das ist insbesondere doof, weil die Artikel-Inhalte länger sind, als der Viewport, so dass man immer nur den ersten teil des Inhalts lesen kann.

Ist das ein Bestandteil des Javascrips und kann ich das irgendwo deaktivieren, so dass die Website ganz normal scrollt?

Vielen Dank und viele Grüße
Timo

**Comment by denniserdmann** [comment]
Moin Timo,

kannst du dein Problem nochmal genauer beschreiben? Ich verstehe leider nicht was du meinst. Oder vielleicht kannst du eine Demo (meinetwegen auch per Mail) zur Verfügung stellen.

**Comment by intradesign** [comment]
Hallo Dennis,
Vielen Dank, ich habe dir eben eine E-Mail geschickt.

**Comment by denniserdmann** [comment]
Es hat sich herausgestellt, dass es ein CSS-Problem war, dass unabhängig von der Navigation erzeugt wurde.
