### ISSUE TITLE
Keine Funktion mehr nach Update auf 4.9.17

### ISSUE THREAD

**Issue by spacefront** [erdmannfreunde/contao-onepage-navigation#18]
Hallo,

leider geht die Navigation nach dem Update auf die 4.9.17/18  nicht mehr.

Bis zu 4.9.16 war noch alles OK.
Ich habe den Fehler auf 3 Seiten.
z.B.
Viele Grüße und Danke

Alex

**Comment by spacefront** [comment]
https://www.cs-value.de/#online-beratung

**Comment by denniserdmann** [comment]
Heute kam 4.9.19 raus und behebt ein Fehler mit Inserttags. Kannst du es mal damit testen?

**Comment by spacefront** [comment]
Hallo.

Nein unter 4.9.19 ist der Fehler auch da. Ich kann euch gerne zugangdaten schicken wenn es der Sache dienlich ist..
VG
Alex

**Comment by denniserdmann** [comment]
Moin Alex,

ich habe es unter 4.9.19 und 4.11.8 getestet und kann den Fehler nicht nachvollziehen. Hättest du nicht geschrieben, dass es unter 4.9.16 noch funktionierte, hätte ich es auf eine ältere Version der Onepage-Navigation geschoben.

Bitte prüfe dennoch in deiner Installation, ob das Feld für die Sprungmarke ausgefüllt ist. Dieser Wert wird als ID für die Navigation verwendet. Bei dir heißen sie z.B. noch `article-1` (das ist ein Indiz dafür, dass das Feld leer sein könnte).  

Wenn die Felder befüllt, aber nicht verwendet werden, könnte es auch mit einer Änderung von `mod_article` zu tun haben. Contao-seitig wurde hier allerdings längere Zeit nichts geändert, es ist also eher unwahrscheinlich, dass es in direktem Zusammenhang mit dem Contao Update steht.

Dritte Möglichkeit wäre ein Update einer anderen Erweiterung, die nun mit der Onepage-Navigation kollidiert. Hier könnte der Debug-Modus dir u.U. helfen, zu erkennen, von wo das Template geladen wird.

Wenn alles nichts hilft, sende mir bitte eine Mail mit Zugangsdaten. Dann schaue ich nächste Woche, ob ich etwas finde.

Viele Grüße,
Dennis

**Comment by spacefront** [comment]
Moin Dennis,

komisch.

Ich habe jetzt mal alle Erweiterungen entfernt (ohne DB Update) die in beiden Installationen vorkommen.

Das Ergebnis ist das gleiche.

Komisch auch warum er Artikel#123 usw. reinschreibt – das war doch früher nicht so oder?
Das mit dem Debug verstehe  ich leider nicht ganz wie ich das machen kann😯

Bei einer 5.9.16 die an sich den gleichen Erweiterung stamm hat geht noch alles die onepage ist aber schon die 1.1.6.

Ich bin etwas überfragt woran es noch scheitern könnte.

Mein JS im Seitentamplate habe ich auch rausgenommen.

Login kommt per Mail

Viele Grüße
Alex
