### ISSUE TITLE
Klasse "active" wird nicht gesetzt

### ISSUE THREAD

**Issue by netgroupgmbh** [erdmannfreunde/contao-onepage-navigation#19]
Hallo,
ich habe die Extension letzte Woche installiert (1.1.16) und sie funktioniert grundsätzlich erst mal (Contao 4.9.14). 
Nur setzt sie die Klasse "active" nicht, wenn man die Menüpunkte anklickt. 
Zu sehen unter: https://www.asi-online.de/beratungsangebot.html

Danke für einen Tipp!
Tanja

**Comment by denniserdmann** [comment]
Moin Tanja,

die Erweiterung nutzt jQuery, um die Menüpunkte und das Scrollen zum Inhalt zu realisieren. Es sieht aber nicht so aus, als hättest du die `j_onepage_navigation.html5` im Seitenlayout bei jQuery aktiviert.

**Comment by netgroupgmbh** [comment]
Moin Dennis,
das war's ... manchmal sind es die kleinen Dinge ...
DANKE
:)TANJA
