### ISSUE TITLE
C4.13 Attempted to load class "Utf8" from namespace "Patchwork".

### ISSUE THREAD

**Issue by andre5tz** [erdmannfreunde/contao-onepage-navigation#21]
Hallo,

ich habe gerade in einer Testinstallation eine Fehlermeldung erhalten.

> Internal Server Error
> 
> Attempted to load class "Utf8" from namespace "Patchwork". Did you forget a "use" statement for another namespace?

In der Log-Datei finde ich die folgende Zeile:
> [2022-02-25T11:02:06.352375+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load class "Utf8" from namespace "Patchwork". Did you forget a "use" statement for another namespace?" at /.../vendor/erdmannfreunde/onepage-navigation/src/Modules/ModuleOnepageNavigation.php line 39 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load class \"Utf8\" from namespace \"Patchwork\".\nDid you forget a \"use\" statement for another namespace? at /.../vendor/erdmannfreunde/onepage-navigation/src/Modules/ModuleOnepageNavigation.php:39)"} []

Der Fehler tritt auf, wenn ich einen Artikel bearbeiten möchte (Stiftsymbol), in dem das Modul Onepage-Navigation eingebunden ist.
Unter Contao 4.9 gibt es das Problem nicht. Ich kann mit der Meldung nichts anfangen, denke aber es kann nicht schaden, es hier zu melden.

Falls ich bei der Lösung helfen kann, testen oder Zugang zur Testumgebung, mache ich das gerne.

Vielen Dank

VG
André

**Comment by denniserdmann** [comment]
Moin André,

vielen Dank fürs Melden. Das Problem ist mit der neuen Version 1.1.9 behoben.
