### ISSUE TITLE
Ajax-Post-Action schlägt fehlt beim Laden der Subpalette `addNavigation`

### ISSUE THREAD

**Issue by OMOSde** [erdmannfreunde/contao-onepage-navigation#23]
Contao 4.13.13
PHP 8.1
Bundle 2.0.0

Beim Klick auf `Als Navigationspunkt hinzufügen` (im Artikel) gibt der POST-Request zum Laden der Palette einen 400er Fehler. (vendor\contao\core-bundle\src\Resources\contao\classes\Ajax.php:L440)

Das Contao System-Log enthält: `Field "addNavigation" is not an allowed selector field (possible SQL injection attempt)`

Beim Ajax-Request scheint im `__selector__` das Feld `addNavigation` zu fehlen. Mir ist leider nicht klar warum das so ist.

Problem tritt auch in einem 2. System auf.

**Comment by denniserdmann** [comment]
Kannst du bitte einmal prüfen, ob das Problem auch in cobntao 4.13.11 auftritt? Es gibt aktuell mehrere Probleme mit JS [(Beispiel hier)](https://github.com/contao/contao/issues/5508) im Backend der aktuellen 4.13.13. Wenn er dennoch auftritt, kann ich ausschließen, dass der Fehler ebenfalls in Contao liegt.

**Comment by OMOSde** [comment]
Das kann ich gerne tun.

Ansonsten hier mein aktueller Workaround (im AppBundle):

```
<?php

// src/Resources/contao/dca/tl_article.php
declare(strict_types=1);

/**
 * Palettes
 */
$GLOBALS['TL_DCA']['tl_article']['palettes']['default'] = str_replace('{onepage_legend},addNavigation', '{onepage_legend},addNavigation,navigation_title,navigation_jumpTo', $GLOBALS['TL_DCA']['tl_article']['palettes']['default']);

/**
 * Fields
 */
$GLOBALS['TL_DCA']['tl_article']['fields']['addNavigation']['eval']['submitOnChange'] = false;

```

**Comment by OMOSde** [comment]
Das Problem besteht auch in einer Contao 4.13.11!

**Comment by denniserdmann** [comment]
Ich habe es in Contao 4.9.36 und 5.0.6 geprüft und dort taucht der Fehler nicht auf. Es ist nicht auszuschließen, dass der Fehler dennoch in der 4.13 ist, aber ich würde zumindest die Fehlersuche ein wenig ausweiten. Hast du andere Extensions im Einsatz, die evtl. das Problem mitverursacht haben können?

Vielleicht eine andere Ajax-Extension? 

Ansonsten kann ich keinen Fehler entdecken und würde zwar das Verhalten weiter beobachten, aber erstmal keine weiteren Schritte unternehmen.

**Comment by OMOSde** [comment]
Ich habe es nun in einer blanken 4.13.13 (PHP 8.1, Bundle 2.0.0) getestet und hier tritt das Problem nicht auf. Ich werde die Tage versuchen die Ursache in den anderen Installationen zu finden.

Vielen Dank für deine Mühen.

**Comment by netgroupgmbh** [comment]
@OMOSde Ich hatte das Problem auch, das lag an einer anderen Erweiterung (Artikel-Hintergrund-Bild), die anderen Subpalettes verhindert hat.

**Comment by OMOSde** [comment]
Wir haben das Problem nun auf unserer Seite in einem internen Bundle ausfindig machen können. 

Danke für eure Mühen.
