### ISSUE TITLE
scroll-margins being ignored

### ISSUE THREAD

**Issue by asaage** [erdmannfreunde/contao-onepage-navigation#25]
I used 
```css
.onepage_article {
    scroll-margin-top: 6rem;
}
```
to prevent content from sliping underneath a sticky/fixed header but the onepage_navigation.js uses offsetTop and does not consider scroll-margins.
I tinkered around to substract the margin but then i figured it's easier to just ditch [these lines](https://github.com/erdmannfreunde/contao-onepage-navigation/blob/main/src/Resources/public/onepage_navigation.js#L21-L29).
and optionally set ```scroll-behavior: smooth;``` on the html element on init.

That would allow for css scroll-margins and for rare cases of horizontally scrolling layouts.

https://github.com/erdmannfreunde/contao-onepage-navigation/issues/7

**Comment by denniserdmann** [comment]
I ran into the same problem some days ago. The lines you mentioned are only for one purpose: exclude clicks in the browser history (if you wish to). If you use smooth scrolling via css, then your users will have every clicked section in their browser history. This is ok if you have a documentation, but if the user comes from google and just wants to go back to check other results, she will have to press the backwards buttons a few times more often then expected.

I don't have a solution for this yet and hope someday browsers will support the combination of JS scrollBehaviour and  options added via css

**Comment by asaage** [comment]
You mean ```'pushUrl': false``` would not work anymore?
Okay - i can live with that and will keep my modified version.

**Comment by denniserdmann** [comment]
> You mean 'pushUrl': false would not work anymore?

Yes, you don't have a choice. Clicks will always lead to entries in browser history. But that's not a problem with the extension, but with how browsers safe every click on a link (doesn't matter if inline or not)

**Comment by asaage** [comment]
From the distant past i remember a technique where you would scroll to an invisible anchor which was css-shifted outside of the element itself.

```html
<div class="mod_article  block">
    <a id="foo" class="onepage_anchor"></a>
    ...
</div>

instead of 

<div class="mod_article  onepage_article block" id="foo">
    ...
</div>
```
could be a solution but would probably need adjustments in the IntersectionObserver.

**Comment by denniserdmann** [comment]
Unfortunately not 😒
Just tested it and it doesn't matter if it's an anchor with id or the article with id itself. But it's good to see, that this problem also exists for sites like wikipedia and their TOC. 

So i will not investigate further in a solution that mostly exists in my head.

**Comment by asaage** [comment]
🤷‍♂️ works  with
```css
.onepage_anchor {
  position: absolute;
  margin-top: -7rem;
}
```
but admittedly it looks a bit hacky.
