### ISSUE TITLE
module breaks the 404 error-page

### ISSUE THREAD

**Issue by asaage** [erdmannfreunde/contao-onepage-navigation#26]
If the onepage-navigation-module is placed in a layout that is used by the 404-Pagetype the error-page does not work anymore.
This can be mitigated if you select a rootpage for the module.

**Comment by christianbarkowsky** [comment]
Hey @asaage, magst du mir das mal zeigen?

**Comment by denniserdmann** [comment]
i ca confirm that with contao 5 and onepage-navigation 2.X

**Comment by christianbarkowsky** [comment]
i will fix that @asaage @denniserdmann

**Comment by christianbarkowsky** [comment]
Please test the dev-main @denniserdmann @asaage

**Comment by asaage** [comment]
@christianbarkowsky works like expected now 👍🏼.
