### ISSUE TITLE
[InvalidArgumentException]

### ISSUE THREAD

**Issue by anuijen** [erdmannfreunde/contao-onepage-navigation#3]
When I try to install the extension via composer, I get the following message:

[InvalidArgumentException]                                                                                                                           
Could not find package ErdmannFreunde/contao-onepage-navigation at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability    

I am using Contao 4.48 - what am I doing wrong?

**Comment by denniserdmann** [comment]
using `composer require erdmannfreunde/onepage-navigation` should do the trick. I was not able to use the **contao-** prefix as this already exists from the original extension by Sascha aka contao.kitchen

**Comment by anuijen** [comment]
Hey Dennis, thank you for your fast reply. I've tried to use the suggested command, but got this error message:

```
Content-Length mismatch, received 546935 bytes out of the expected 2059127
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

**Comment by denniserdmann** [comment]
I tried it minutes before and for me it was working, even with Contao 4.4.8. Could be a problem with packages.org itself.

To make sure composer is using the latest version, you can clear the composer cache with `composer clearcache` and try it again.

**Comment by anuijen** [comment]
This worked. Thank you again for your support!
