### ISSUE TITLE
"active" wird nicht immer gesetzt

### ISSUE THREAD

**Issue by JensenR** [erdmannfreunde/contao-onepage-navigation#30]
Habe die OnePager Navigation eingebaut (Contao 5.3). Nach dem Stylen der Menüzustände habe ich festgestellt, dass nicht immer der "active"-Zustand gesetzt wird. Erst, wenn ich im einzelnen ".onepage_article" jeweils ein großes Padding oben und unten hinzugebe funktioniert es, sieht aber dann sehr auseinander gezogen aus.  Der Inhalt ist eigentlich grundsätzlich lang genug. 

Die selbe Problematik hatte ich bei einer anderen Webseite auch. (Contao 4.9)

Ist das ein Problem oder Einstellungssache?

**Comment by denniserdmann** [comment]
Beides: Problem und Einstellungssache. Es gibt eine Einstellung `offset`, die du anpassen kannst, siehe https://github.com/erdmannfreunde/contao-onepage-navigation/blob/main/src/Resources/contao/templates/js_onepage_navigation.html5

Der Standardwert 30 besagt, dass 30% des Inhalts sichtbar sein müssen, damit der Menüpunkt aktiv wird. Bei kurzen Artikel kann es aber dazu führen, dass ein Menüpunkt übergangen wird, weil bereits vom nächsten Artikel 30% sichtbar sind.

Du kannst mit dem Wert experimentieren und vielleicht findest du eine Lösung, die für dein Layout passt. Bei SIRIUS verwenden wir die Standardeinstellung, arbeiten aber auch mit Abständen, siehe https://sirius-2.contao-theme.de

**Comment by JensenR** [comment]
Danke für die schnelle Antwort. Habe nun etwas herumprobiert und mit "offset: 50" die perfekte Einstellung für meinen Content gefunden.

**Comment by christianbarkowsky** [comment]
Sollte die Doku an der Stelle erweitert werden @denniserdmann?

**Comment by denniserdmann** [comment]
@christianbarkowsky Ich werde es mir überlegen.
