### ISSUE TITLE
[Contao 4.5.X] article order doesn't effect navigation order

### ISSUE THREAD

**Issue by denniserdmann** [erdmannfreunde/contao-onepage-navigation#4]
It looks like articles are sorted by id and not their order in the article structure.

To reproduce: 
1. create 2 articles with onepage-navigation
2. switch order for articles or create the second before the first article

**Comment by bastibuck** [comment]
My tests (Contao 4.4.7) actually showed the correct order after reordering and/or creating articles in a different order than what their IDs represent. Can you please recheck on your install?

**Comment by denniserdmann** [comment]
You're right. This is a problem in Contao 4.5.X, not in Contao 4.4.X.
Took me 1 hour to find this out.

**Comment by bastibuck** [comment]
So is it a known issue in 4.5.x and we don't need to change anything?

**Comment by denniserdmann** [comment]
I don't think so.

**Comment by denniserdmann** [comment]
Adding sorting explicitly as suggested in https://github.com/ErdmannFreunde/contao-onepage-navigation/blob/d8837c7ce7fdc0254711a69f19424fe886161777/src/Modules/ModuleOnepageNavigation.php#L65 is working for me
