### ISSUE TITLE
Reference page does not work as expected

### ISSUE THREAD

**Issue by Balindil** [erdmannfreunde/contao-onepage-navigation#6]
I have a page with the following structure:
- Landing_Page (width onepage navigation)
   -- Article_1
   -- Article_2
   -- Article_3
- Page_2
- Page_3

If I want to have the Onepage menu on the subpages, so that I can get back to the landing page, I set the landing page as a reference page in the module.

But as a result I get links in the navigation like Page_2#Article_1 or Page_3#Article_2 and not as it should have been Landing_Page#Article_1.

**Comment by denniserdmann** [comment]
You're right. I added the correct page alias of the root page in 891da2b08e459c76b7f892889ac4892ce2f83426 

Can you verify this by using the latest commit in develop branch?

**Comment by Balindil** [comment]
~~What do I have to put in the composer. json to test it?
At the moment it is: "^1.0"~~

I've tried it and it works.
