### ISSUE TITLE
[Help needed] Support for fixed header

### ISSUE THREAD

**Issue by V15** [erdmannfreunde/contao-onepage-navigation#8]
The code I provided in #7 works fine in all modern Browsers but not in Internet Explorer 11 if the content of the anchor is higher than the browser window. In this case it scrolls to the position where it should scroll to (anchor + fixed header) and than jumps up to the real anchor position.

If the content is only a couple of sentences and fits in the browser window without the need to scroll down to read all of the sentences - it works fine as well.

I could not find a solution for this problem.

**Comment by denniserdmann** [comment]
You're right. I have the same problem in IE 11, but unfortunately no solution for this. This problem occur when overtime you want to add an offset to the scroll prosition (not only when using a fixed header). 

Maybe you find a solution when you search for "jquery scrolltop wrong position".

**Comment by V15** [comment]
I did search for quite some time for a solution and tried a couple of things without success.

But now I found an easy workaround:
Keep the content withe anchor short :-)

If you have to much content, copy it in an separate article without an anchor and keep only the headline in the article with the anchor. Works for me.

**Comment by V15** [comment]
This Problem is present on android devices (small screens like phones) as well - even with modern browsers!

To fix this issue I used a (dirty) workaround: I created empty articles as anchors and for display in Navigation and created a new article below that contains the content. Not pretty but it seems to work on all devices...

**Comment by denniserdmann** [comment]
Guess I found the bug. After scrolling to the right position, the script focusses on the current article and jumps to it. Removing this [lines 31-32 in j_onepage_navigation.html5 ](https://github.com/ErdmannFreunde/contao-onepage-navigation/blob/master/src/Resources/contao/templates/j_onepage_navigation.html5#L31-L32)template should do the trick.

Can you test this?

**Comment by V15** [comment]
I will test this in the next couple days.
